export const es = {
    front: {
         
        title: "Crea tu quiz personalizado",
        //  description: "Desafíate a ti mismo: ¡sigue practicando hasta que seas imparable!",
        description: "Escoge la asignatura que quieras repasar",
    },
    login: {
        title: "Inicio de sesión",
        description: "Introduce tu correo de alumnos UPM para crear tu quiz.",
        preTerms: "Al registrarme, confirmo que he leído y acepto los",
        terms: "Términos de Uso",
        prePrivacy: "y la",
        privacy: "Política de Privacidad",
    },
    subject: {
        title: "Asignatura: ",
        description: "¡Realiza tantos cuestionarios como desees sobre los temas del curso!",
        topic: "Tema",
        preSubtopic: "Subtema anterior",
        choose: "Elige un tema",
        choose2: "Elige el tema que deseas repasar",
        subtopic: "Subtema",
        settings: "Ajustes del cuestionario",
        difficulty: "Dificultad",
        choosedif: "Elige la dificultad y el número de preguntas",
        easy: "Fácil",
        medium: "Medio",
        advanced: "Avanzado",
        nquestions: "Número de preguntas",
        createtest: "Crear test",
        saveemail: "Guardar email",
        alertEmptyMail: "Debes introducir tu email de alumno para empezar ",
        alertUncheckedTermsPolicy: "Debes aceptar los Términos de uso y la Política de Privacidad",
        alertUPMMail: "El email debe ser de alumno de la UPM",
        alertPickLang: "Debes elegir tema para empezar",
        alertPickTopic: "Debes elegir sub-tema para empezar",
    },
    loading: {
        title: "Generando Test...",
        description: "(Puede tardar unos segundos...)"
    },
    instructions: {
        title: "Instrucciones",
        line1: "Para enviar tu respuesta, presiona",
        respond: "Responder",
        line2: "Si alguna pregunta crees que no está bien redactada o es incorrecta, presiona",
        report: "Reportar pregunta incorrecta",
        line3: "¡Para obtener tu nota final deberás responder a ",
        line4: "todas las preguntas!"
    },
    quizpage: {
        back: "Volver",
        instructions: "Instrucciones",
        testof: "Test de",
        about: "sobre",
        subjectof: "Nombre de la asignatura:",
        finish: "Finalizar",
    },
    question: {
        answer: "Responder",
        answered: "Respondida",
        report: "Reportar pregunta incorrecta",
        reported: "Pregunta reportada",
        question: "Pregunta",
        explanation: "Explicación",
    },
    endscreen: {
        title: "Nota:",
        back: "Volver a la asignatura",
        repeat: "Repetir test"
    },
    dashboard: {
        title: "Dashboard del profesor",
        subject: "Asignatura",
        infoQuestions: "Información sobre las preguntas respondidas",
        totalQuestions: "Total de preguntas",
        questionsReported: "Preguntas reportadas",
        questionsRight: "Preguntas correctas",
        questionsWrong: "Preguntas incorrectas",
        insights: "Insights generados por el modelo sobre los conocimientos de los alumnos",
        back: "Volver",
        choose: "Elige la Asignatura para ver el dashboard:",
        reportTitle: "Reporte sobre conocimientos de los alumnos"
    },
    footer: {
        title: "Universidad Politécnica de Madrid - Grupo de Internet de Nueva Generación",
    },
    common: {
        loading: "Cargando...",
        error: "Error",
        notFound: "No encontrado"
    },
    reports: {
        title: "Reportes",
        comparator: "Comparador",
        scomparator: "Salir del comparador",
        fechainicio: "Fecha inicio",
        fechafin: "Fecha Fin",
        description: "Escoge la asignatura de la que quieras obtener estadísticas",
        subtitle0: "Preguntas reportadas",
        subtitle1: "Evaluar reportadas",
        pregreport1: "Número de preguntas reportadas",
        pregreport2: "Número de preguntas reportadas evaluadas",
        pregreport3: "Número de preguntas reportadas sin evaluar",
        graph0_title: " Motivos de reporte",
        porcentaje: "Porcentaje",
        subtitle2: "Frecuencia y Porcentaje de acierto según Dificultad",
        dificultad: "Dificultad",
        preguntas: "Preguntas",
        acierto: "Acierto",
        porcentaje_acierto: "Porcentaje Acierto",
        numero_preguntas: "Número de Preguntas",
        graph1_title: "Porcentaje aciertos por Dificultad",
        graph2_title: "Frecuencia de preguntas por Dificultad",
        subtitle3: "Frecuencia y Acierto por cada Tema de",
        graph3_title: "Porcentaje aciertos por cada Tema",
        graph4_title: "Frecuencia de preguntas por cada Tema",
        tema: "Tema",
        subtitle4: "Frecuencia y Acierto de cada Subtema por Temas",
        graph5_title: "Porcentaje aciertos por cada Subtema de",
        graph6_title: "Frecuencia de preguntas por cada Subtema de",
        subtema: "Subtema",
        subtitle5: "¿Cuándo se ha utilizado más la aplicación?",
        pormeses: "Número de preguntas respondidas",
        update: "Actualizar",
        total_questions: "Total de preguntas generadas por la herramienta",
        total_questions_period: "Total de preguntas generadas en el periódo seleccionado"
    },
    pregreports: {
        opt: "OPCIONES",
        exp: "EXPLICACIÓN",
        ans: "RESPUESTA CORRECTA",
        title: "Evaluar pregunta",
        button: "Enviar evaluación",
        ver: "Ver:",
        todas: "Todas",
        noEvaluadas: "No evaluadas",
        desde: "Desde:",
        hasta: "Hasta:",
        actualizar: "Actualizar",
        numeroReportadas: "Número de preguntas reportadas:",
        numeroSinEvaluar: "Número de preguntas reportadas sin evaluar:",
        evaluarPregunta: "Evaluar Pregunta",
        evaluacion: "Evaluación:",
        todoCorrecto: "Todo Correcto",
        tieneFallo: "La pregunta tiene algún fallo",
        todoCorrectoFallo: "¿Todo correcto o tiene algún fallo?",
        otro: "Otro:",
        anterior: "Anterior",
        siguiente: "Siguiente",
        pagina: "Página",
        de: "de",
        cargando: "Cargando datos...",
        error: "Error:"
    },
    evaluationComments: {
        redaccionConfusa: "Redacción confusa",
        opcionesMalFormuladas: "Opciones mal formuladas",
        opcionesRepetidas: "Opciones repetidas",
        variasOpcionesCorrectas: "Varias opciones correctas",
        ningunaOpcionCorrecta: "Ninguna opción correcta",
        respuestaMarcadaIncorrecta: "Respuesta marcada incorrecta",
        explicacionErronea: "Explicación errónea",
        fueraDeTemario: "Fuera de temario",
        otro: "Otro"
    }
};