'use client'

import './globals.css'
// import i18n (needs to be bundled ;))
import "./i18n";

import { Inter, Poppins, Lato } from 'next/font/google'
import { useTranslation } from "react-i18next";

const poppins = Poppins({ subsets: ['latin'], weight: '400' })

const inter = Inter({ subsets: ['latin'] })
const lato = Lato({ subsets: ['latin'], weight: '400' })


// can only do this if it's a server component
// export const metadata = {
//     title: 'AI Quiz Generator',
//     description: 'Generated by create next app',
// }

import Script from 'next/script'

export default function RootLayout({ children }) {
    const { t, i18n } = useTranslation();

    return (
        <html lang='en'>
            <head>
                <title>{t("front.title")}</title>
                <link rel="icon" href="/my-favicon-32x32.png" type="image/x-icon"></link>
            </head>
            <body className={`${inter.className} relative bg-blue-200`}>
               

                {/* <main className='relative z-10 max-w-7xl mx-auto sm:px-16 px-6'> */}
                    {children}
                {/* </main> */}
            </body>
        </html>
    )
}
