export const topics = {
    java: [
        'Declaración de variables',
        'Tipos de datos, operadores y expresiones',
        'Bucles y condicionales',
        'Uso de Break y Continue',
        'Clases y objetos',
        'Comandos try, catch y finally',
        'Manejo de excepciones',
    ],
    python: [
        'Funciones, argumentos y valores de retorno',
        'Funciones lambda',
        'Condicionales y bucles',
        'Uso de Break y Continue',
        'Listas, tuplas y diccionarios',
        'Clases, objetos y herencia',
    ],
    javascript: [
        'Historia y evolución',
        'Características principales',
        'Sintaxis básica',
        'Tipos de datos',
        'Const, let, var',
        'Funciones',
        'Paso por referencia vs paso por valor',
        'Tipos primitivos',
        'Objetos JavaScript',
        'Clases y herencia',
        'Notación de puntos y corchetes',
        'Clonado de objetos',
        'Notación arrow',
        'This, bind, call, apply',
        'Closures',
        'Modo estricto',
        'Modulos ES6 y CommonJS',
        'Métodos de arrays (forEach, map, filter, reduce)',
        'Asincronía: callbacks, promesas, async/await',
        'Manejo de errores',
        'JSON',
    ],
    javascript_cliente: [
        'Características principales',
        'Eventos y manejo de eventos',
        'DOM y manipulación del DOM',
        'Objeto document y window',
        'Temporizadores',
        'SessionStorage y LocalStorage',
        'Alert, confirm y prompt',
        'AJAX y fetch API',
    ],
    node: [
        'Características principales',
        'Process',
        'NPM y versionado paquetes',
        'File System',
        'Sistema de archivos',
        'Streams',
        'Eventos',
        'package.json',
    ],
    react: [
        'Creación y uso de componentes',
        'Props',
        'State',
        'Sintaxis y uso de JSX',
        'Métodos del ciclo de vida',
        'Actualización de estado',
        'Manejo de eventos',
        'React Router',
    ],
    http: [
        'URLs',
        'Formato peticiones HTTP',
        'Cabeceras HTTP',
        'Métodos POST, PUT, GET, DELETE, HEAD',
        'Códigos de respuesta',
        'Caché web',
        'Gestión de estado: parámetros ocultos, cookies, sesión',
    ],
    html:[
        'Estructura básica de un documento HTML',
        'Atributos HTML',
        'Id y clase HTML',
        'Etiquetas de texto',
        'Etiquetas de hipervínculo',
        'Etiquetas de imagen',
        'Etiquetas de lista',
        'Tablas',
        'Formularios',
        'Etiquetas de audio y video',
    ],
    css: [
        'Características principales',
        'Sintaxis básica',
        'Selectores y prioridad',
        'Modelo de caja: margin, padding, border',
        'Unidades de medida',
        'Posicionamiento',
        'Display y visibility',
        'Flexbox',
        'Grid',
        'Float y clear',
        'Diseño responsive',
        'Media queries',
        'Variables CSS',
    ],
    swift: [
        'Variables y constantes',
        'Opcionales',
        'Condicionales y bucles',
        'Uso de guard y defer',
        'Clases, estructuras y métodos',
        'Uso de if let y guard let',
        'Nil coalescing',
    ],
    intro_nosql: [
        'las 5 Vs del Big Data',
        "Data LifeCycle Management",
        "Data Value Pyramid",
        "Sistema Distribuido, Particionamiento y Replicación",
        "Teorema CAP",
        "Teorema BASE",
        "Teorema ACID"
    ],
    json: [
        'Estructura de un documento JSON',
        'Tipos de datos JSON',
        'Arrays y objetos JSON',
        'Que es JSON Schema y para que sirve',
        'Estructura de un documento JSON Schema',
    ],
    schema_design: [
        'Modelo de datos no relacional o NoSQL',
        'Modelo de datos orientado a documentos con MongoDB'    
    ],
    mongosh: [
        'Comandos básicos',
        'Operaciones CRUD',
        'Operaciones de consulta',
        'Operaciones de actualización',
        'Operaciones de eliminación'
    ],
    mongodb_aggregation: [
        'Operadores de agregación',
        'Operadores de proyección',
        'Operadores de agrupación',
        'Operador unwind'
    ],
}
