export const topics = {
    java: [
        'Declaración de variables',
        'Tipos de datos, operadores y expresiones',
        'Bucles y condicionales',
        'Uso de Break y Continue',
        'Clases y objetos',
        'Comandos try, catch y finally',
        'Manejo de excepciones',
    ],
    python: [
        'Funciones, argumentos y valores de retorno',
        'Funciones lambda',
        'Condicionales y bucles',
        'Uso de Break y Continue',
        'Listas, tuplas y diccionarios',
        'Clases, objetos y herencia',
    ],
    javascript: [
        'Sintaxis básica y estructuras de control',
        'Tipos de datos',
        'Variables',
        'Funciones',
        'Métodos de arrays (forEach, map, filter, reduce)',
        'Eventos y manejo de eventos',
        'DOM y manipulación del DOM',
        'Asincronía',
        'AJAX y fetch API',
        'Manejo de errores',
        'Testing',
    ],
    react: [
        'Creación y uso de componentes',
        'Props',
        'State',
        'Sintaxis y uso de JSX',
        'Métodos del ciclo de vida',
        'Actualización de estado',
        'Manejo de eventos',
        'React Router',
    ],
    html: [
        'Etiquetas',
        'Atributos id, class, src',
        'Método GET',
        'Método POST',
    ],
    css: [
        'Slectores #id y .class',
        'Propiedades de estilo',
        'Conceptos del Box Model',
        'Propiedades de posicionamiento',
        'Flexbox',
        'Grid',
    ],
    swift: [
        'Variables y constantes',
        'Opcionales',
        'Condicionales y bucles',
        'Uso de guard y defer',
        'Clases, estructuras y métodos',
        'Uso de if let y guard let',
        'Nil coalescing',
    ],
}
